### PR TITLE
Use database mutex locking

### PR DESCRIPTION
**Pull request by Silex**
Make sure to read #325 first.

### CODE REVIEW

**Comment by brendon** [comment]
Hi @Silex, good to see you active on this again. I've been working on the repo today cleaning up the tests on travis (dropping Rails 3.2-4.1 support and old ruby support) so be sure to check out master.

**Comment by brendon** [comment]
Also, don't edit the gemfiles directly, edit `Appraisals` instead.

**Comment by Silex** [comment]
@brendon: not really working on this, just recreating the PR because I had deleted my fork but was able to recover the commits.

**Comment by brendon** [comment]
Thanks @Silex, that's all good :)

**Comment by c2ofh** [comment]
Could this PR maybe could fix the DeadLock-Problem? @brendon

**Comment by brendon** [comment]
Hi @c2ofh, this one kind of languished. If you'd like to create a new PR based off this and get the tests green then I'd definitely look at it. Key here will be making it an opt-in thing as it could have wide reaching consequences on some codebases.

**Pull request closed without merging**
